name: Publish

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: "startsWith(github.event.head_commit.message, '[RELEASE]')"
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"
            - name: Install Dep
              run: npm ci
            - name: Build
              run: npm run build
            - name: Publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
