name: Version Increment

on:
    push:
        branches:
            - main

jobs:
    version:
        runs-on: ubuntu-latest
        env:
            COMMIT_MSG: ${{ github.event.head_commit.message }}
            PATCH: ${{ startsWith(github.event.head_commit.message, '[PATCH]') || 'false' }}
            MINOR: ${{ startsWith(github.event.head_commit.message, '[MINOR]') || 'false' }}
            MAJOR: ${{ startsWith(github.event.head_commit.message, '[MAJOR]') || 'false' }}
        if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
            - name: Set User
              run: git config --global user.name 'christoph_xd'
            - name: Set Email
              run: git config --global user.email 'c.brandau91@gmail.com'
            - name: Set ENV
              if: "${{ env.PATCH == 'true' }} || ${{ env.MINOR == 'true' }} || ${{ env.MAJOR == 'true' }}"
              run: |
                  if [ ${{ env.PATCH }} == 'true' ];then 
                      echo "RUN PATCH"
                      echo "RELEASE_TYPE='patch'" >> $GITHUB_ENV
                      echo "RELEASE_PREFIX='[PATCH]'"
                  elif [ ${{ env.MINOR }} == 'true' ];then
                      echo "RUN MINOR"
                      echo "RELEASE_TYPE='minor'" >> $GITHUB_ENV
                      echo "RELEASE_PREFIX='[MINOR]'"
                  elif [ ${{ env.MAJOR }} == 'true' ];then
                      echo "RUN MAJOR"
                      echo "RELEASE_TYPE='major'" >> $GITHUB_ENV
                      echo "RELEASE_PREFIX='[MAJOR]'"
                  else
                      echo "RELEASE_TYPE=''" >> $GITHUB_ENV
                      echo "RELEASE_PREFIX='"
                  fi
            - name: Increment Version
              if: "${{ env.PATCH == 'true' }} || ${{ env.MINOR == 'true' }} || ${{ env.MAJOR == 'true' }}"
              run: |
                  if ! [ ${{ env.RELEASE_TYPE }} == '' ]; then
                      npm version ${{ env.RELEASE_TYPE }} -m "[RELEASE] '${{ env.RELEASE_PREFIX }}' %s"
                  fi
            - name: Git push
              if: "${{ env.PATCH == 'true' }} || ${{ env.MINOR == 'true' }} || ${{ env.MAJOR == 'true' }}"
              run: |
                  if ! [ ${{ env.RELEASE_TYPE }} == '' ]; then
                      git push
                  fi
